/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface HandleRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "handleOf"
      | "isAvailable"
      | "logPayment"
      | "registerHandle"
      | "resolve"
      | "setAddress"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AddressUpdated"
      | "HandleRegistered"
      | "PaymentLogged"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "handleOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "isAvailable", values: [string]): string;
  encodeFunctionData(
    functionFragment: "logPayment",
    values: [string, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerHandle",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "resolve", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setAddress",
    values: [string, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "handleOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isAvailable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "logPayment", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerHandle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resolve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setAddress", data: BytesLike): Result;
}

export namespace AddressUpdatedEvent {
  export type InputTuple = [
    handle: string,
    oldOwner: AddressLike,
    newOwner: AddressLike
  ];
  export type OutputTuple = [
    handle: string,
    oldOwner: string,
    newOwner: string
  ];
  export interface OutputObject {
    handle: string;
    oldOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HandleRegisteredEvent {
  export type InputTuple = [handle: string, owner: AddressLike];
  export type OutputTuple = [handle: string, owner: string];
  export interface OutputObject {
    handle: string;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentLoggedEvent {
  export type InputTuple = [
    fromHandle: string,
    toHandle: string,
    from: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
    note: string
  ];
  export type OutputTuple = [
    fromHandle: string,
    toHandle: string,
    from: string,
    to: string,
    amount: bigint,
    note: string
  ];
  export interface OutputObject {
    fromHandle: string;
    toHandle: string;
    from: string;
    to: string;
    amount: bigint;
    note: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HandleRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): HandleRegistry;
  waitForDeployment(): Promise<this>;

  interface: HandleRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  handleOf: TypedContractMethod<[account: AddressLike], [string], "view">;

  isAvailable: TypedContractMethod<[handle: string], [boolean], "view">;

  logPayment: TypedContractMethod<
    [fromHandle: string, toHandle: string, amount: BigNumberish, note: string],
    [void],
    "nonpayable"
  >;

  registerHandle: TypedContractMethod<[handle: string], [void], "nonpayable">;

  resolve: TypedContractMethod<[handle: string], [string], "view">;

  setAddress: TypedContractMethod<
    [handle: string, newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "handleOf"
  ): TypedContractMethod<[account: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "isAvailable"
  ): TypedContractMethod<[handle: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "logPayment"
  ): TypedContractMethod<
    [fromHandle: string, toHandle: string, amount: BigNumberish, note: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerHandle"
  ): TypedContractMethod<[handle: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolve"
  ): TypedContractMethod<[handle: string], [string], "view">;
  getFunction(
    nameOrSignature: "setAddress"
  ): TypedContractMethod<
    [handle: string, newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AddressUpdated"
  ): TypedContractEvent<
    AddressUpdatedEvent.InputTuple,
    AddressUpdatedEvent.OutputTuple,
    AddressUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "HandleRegistered"
  ): TypedContractEvent<
    HandleRegisteredEvent.InputTuple,
    HandleRegisteredEvent.OutputTuple,
    HandleRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "PaymentLogged"
  ): TypedContractEvent<
    PaymentLoggedEvent.InputTuple,
    PaymentLoggedEvent.OutputTuple,
    PaymentLoggedEvent.OutputObject
  >;

  filters: {
    "AddressUpdated(string,address,address)": TypedContractEvent<
      AddressUpdatedEvent.InputTuple,
      AddressUpdatedEvent.OutputTuple,
      AddressUpdatedEvent.OutputObject
    >;
    AddressUpdated: TypedContractEvent<
      AddressUpdatedEvent.InputTuple,
      AddressUpdatedEvent.OutputTuple,
      AddressUpdatedEvent.OutputObject
    >;

    "HandleRegistered(string,address)": TypedContractEvent<
      HandleRegisteredEvent.InputTuple,
      HandleRegisteredEvent.OutputTuple,
      HandleRegisteredEvent.OutputObject
    >;
    HandleRegistered: TypedContractEvent<
      HandleRegisteredEvent.InputTuple,
      HandleRegisteredEvent.OutputTuple,
      HandleRegisteredEvent.OutputObject
    >;

    "PaymentLogged(string,string,address,address,uint256,string)": TypedContractEvent<
      PaymentLoggedEvent.InputTuple,
      PaymentLoggedEvent.OutputTuple,
      PaymentLoggedEvent.OutputObject
    >;
    PaymentLogged: TypedContractEvent<
      PaymentLoggedEvent.InputTuple,
      PaymentLoggedEvent.OutputTuple,
      PaymentLoggedEvent.OutputObject
    >;
  };
}
