/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { HandleRegistry } from "./HandleRegistry";
export * as factories from "./factories";
export { HandleRegistry__factory } from "./factories/HandleRegistry__factory";
